import type { Organization, Donor, Receipt } from './database.types';

interface ReceiptData {
  org: Pick<Organization, 'name' | 'logo_url' | 'contact_email' | 'website' | 'country'>;
  donor: Pick<Donor, 'full_name' | 'phone' | 'email' | 'city'>;
  receipt: Pick<Receipt, 'receipt_number' | 'amount' | 'campaign' | 'payment_method' | 'donation_date' | 'notes'> & { is80G?: boolean };
}

export function generateReceiptHTML(data: ReceiptData): string {
  const { org, donor, receipt } = data;
  const amount = Number(receipt.amount).toLocaleString('en-IN');
  const date = receipt.donation_date
    ? new Date(receipt.donation_date).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })
    : new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
*{margin:0;padding:0;box-sizing:border-box}body{font-family:'DM Sans',sans-serif;color:#1E293B;background:#fff}
.r{max-width:680px;margin:0 auto;padding:40px}
.hd{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:32px;padding-bottom:24px;border-bottom:2px solid #0D6E55}
.on{font-size:20px;font-weight:700;color:#0D6E55;margin-bottom:4px}.od{font-size:12px;color:#64748b}
.tb{text-align:center;margin-bottom:28px}.tt{font-size:18px;font-weight:600;text-transform:uppercase;letter-spacing:2px;color:#0D6E55}
.rn{font-size:13px;color:#64748b;margin-top:4px}
.st{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:1px;color:#94A3B8;margin-bottom:8px}
.dg{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:24px}
.di label{font-size:11px;color:#94A3B8;display:block;margin-bottom:2px}.di span{font-size:14px;font-weight:500}
.ab{background:#f0fdf4;border:1px solid #bbf7d0;border-radius:12px;padding:20px;text-align:center;margin:24px 0}
.al{font-size:12px;color:#64748b;margin-bottom:4px}.av{font-size:36px;font-weight:700;color:#0D6E55}
.bg{display:inline-flex;align-items:center;gap:6px;background:#0D6E55;color:white;padding:6px 14px;border-radius:6px;font-size:12px;font-weight:600;margin-top:12px}
.sa{margin-top:40px;display:flex;justify-content:space-between;padding-top:24px;border-top:1px solid #e2e8f0}
.sl{width:180px;border-bottom:1px solid #1E293B;height:40px;margin-bottom:6px}.sn{font-size:11px;color:#64748b;text-align:center}
.ft{margin-top:32px;padding-top:16px;border-top:1px solid #e2e8f0;text-align:center}.ft p{font-size:11px;color:#94A3B8}
</style></head><body><div class="r">
<div class="hd"><div><div class="on">${org.name}</div>${org.contact_email?`<div class="od">${org.contact_email}</div>`:''}${org.website?`<div class="od">${org.website}</div>`:''}</div>
${org.logo_url?`<img src="${org.logo_url}" style="width:64px;height:64px;border-radius:12px;object-fit:cover" />`:`<div style="width:64px;height:64px;border-radius:12px;background:#0D6E55;display:flex;align-items:center;justify-content:center;color:white;font-size:24px;font-weight:700">${org.name.charAt(0)}</div>`}</div>
<div class="tb"><div class="tt">Donation Receipt</div><div class="rn">${receipt.receipt_number}</div></div>
<div class="st">Donor Information</div>
<div class="dg"><div class="di"><label>Name</label><span>${donor.full_name}</span></div><div class="di"><label>Phone</label><span>${donor.phone||'—'}</span></div><div class="di"><label>Email</label><span>${donor.email||'—'}</span></div><div class="di"><label>City</label><span>${donor.city||'—'}</span></div></div>
<div class="st">Donation Details</div>
<div class="dg"><div class="di"><label>Date</label><span>${date}</span></div><div class="di"><label>Payment</label><span>${receipt.payment_method||'—'}</span></div><div class="di"><label>Campaign</label><span>${receipt.campaign||'—'}</span></div>${receipt.notes?`<div class="di"><label>Ref</label><span>${receipt.notes}</span></div>`:''}</div>
<div class="ab"><div class="al">Amount Received</div><div class="av">₹${amount}</div>${receipt.is80G ? `<div class="bg">✓ Eligible for 80G Tax Exemption</div>` : ''}</div>
<div class="sa"><div><div class="sl"></div><div class="sn">Donor Signature</div></div><div><div class="sl"></div><div class="sn">Authorized Signatory</div></div></div>
<div class="ft"><p>Generated by ImpactLens for ${org.name}</p></div>
</div></body></html>`;
}

export function printReceipt(data: ReceiptData): void {
  const html = generateReceiptHTML(data);
  const w = window.open('', '_blank');
  if (w) { w.document.write(html); w.document.close(); w.focus(); setTimeout(() => w.print(), 300); }
}

export function downloadReceipt(data: ReceiptData): void {
  const html = generateReceiptHTML(data);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = `receipt-${data.receipt.receipt_number}.html`; a.click();
  URL.revokeObjectURL(url);
}

export async function renderReceiptToPDF(data: any): Promise<Blob> {
  const receiptData: ReceiptData = {
    org: {
      name: data.organization.name,
      logo_url: data.organization.logoUrl || null,
      contact_email: null,
      website: null,
      country: null
    },
    donor: {
      full_name: data.donor.name,
      phone: null,
      email: null,
      city: null
    },
    receipt: {
      receipt_number: data.receiptNumber,
      amount: data.amount,
      campaign: null,
      payment_method: data.paymentMethod,
      donation_date: data.date,
      notes: data.is80G ? '80G Exemption' : null,
      is80G: data.is80G
    }
  };

  const fullHtml = generateReceiptHTML(receiptData);
  
  const html = generateReceiptHTML(receiptData);
  return new Blob([html], { type: 'text/html' });
}

export type { ReceiptData };
