/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrgSlugIndexRouteImport } from './routes/$orgSlug/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppUploadRouteImport } from './routes/app/upload'
import { Route as AppSubmissionsRouteImport } from './routes/app/submissions'
import { Route as AppMediaRouteImport } from './routes/app/media'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppApprovalsRouteImport } from './routes/app/approvals'
import { Route as AppAnalyticsRouteImport } from './routes/app/analytics'
import { Route as AppWhatsappIndexRouteImport } from './routes/app/whatsapp/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppSeoIndexRouteImport } from './routes/app/seo/index'
import { Route as AppReceiptsIndexRouteImport } from './routes/app/receipts/index'
import { Route as AppDonorsIndexRouteImport } from './routes/app/donors/index'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as OrgSlugBlogIndexRouteImport } from './routes/$orgSlug/blog/index'
import { Route as AppWhatsappBroadcastRouteImport } from './routes/app/whatsapp/broadcast'
import { Route as AppSettingsTeamRouteImport } from './routes/app/settings/team'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/app/settings/integrations'
import { Route as AppSeoPostIdRouteImport } from './routes/app/seo/$postId'
import { Route as AppSeoIdRouteImport } from './routes/app/seo/$id'
import { Route as AppReceiptsNewRouteImport } from './routes/app/receipts/new'
import { Route as AppDonorsNewRouteImport } from './routes/app/donors/new'
import { Route as AppDonorsIdRouteImport } from './routes/app/donors/$id'
import { Route as AdminOrganizationsIdRouteImport } from './routes/admin/organizations/$id'
import { Route as OrgSlugBlogPostSlugRouteImport } from './routes/$orgSlug/blog/$postSlug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: '/$orgSlug/',
  path: '/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUploadRoute = AppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappIndexRoute = AppWhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoIndexRoute = AppSeoIndexRouteImport.update({
  id: '/seo/',
  path: '/seo/',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsIndexRoute = AppReceiptsIndexRouteImport.update({
  id: '/receipts/',
  path: '/receipts/',
  getParentRoute: () => AppRoute,
} as any)
const AppDonorsIndexRoute = AppDonorsIndexRouteImport.update({
  id: '/donors/',
  path: '/donors/',
  getParentRoute: () => AppRoute,
} as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRoute,
} as any)
const OrgSlugBlogIndexRoute = OrgSlugBlogIndexRouteImport.update({
  id: '/$orgSlug/blog/',
  path: '/$orgSlug/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappBroadcastRoute = AppWhatsappBroadcastRouteImport.update({
  id: '/whatsapp/broadcast',
  path: '/whatsapp/broadcast',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoPostIdRoute = AppSeoPostIdRouteImport.update({
  id: '/seo/$postId',
  path: '/seo/$postId',
  getParentRoute: () => AppRoute,
} as any)
const AppSeoIdRoute = AppSeoIdRouteImport.update({
  id: '/seo/$id',
  path: '/seo/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsNewRoute = AppReceiptsNewRouteImport.update({
  id: '/receipts/new',
  path: '/receipts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDonorsNewRoute = AppDonorsNewRouteImport.update({
  id: '/donors/new',
  path: '/donors/new',
  getParentRoute: () => AppRoute,
} as any)
const AppDonorsIdRoute = AppDonorsIdRouteImport.update({
  id: '/donors/$id',
  path: '/donors/$id',
  getParentRoute: () => AppRoute,
} as any)
const AdminOrganizationsIdRoute = AdminOrganizationsIdRouteImport.update({
  id: '/organizations/$id',
  path: '/organizations/$id',
  getParentRoute: () => AdminRoute,
} as any)
const OrgSlugBlogPostSlugRoute = OrgSlugBlogPostSlugRouteImport.update({
  id: '/$orgSlug/blog/$postSlug',
  path: '/$orgSlug/blog/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/media': typeof AppMediaRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/upload': typeof AppUploadRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$orgSlug/blog/$postSlug': typeof OrgSlugBlogPostSlugRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
  '/app/donors/$id': typeof AppDonorsIdRoute
  '/app/donors/new': typeof AppDonorsNewRoute
  '/app/receipts/new': typeof AppReceiptsNewRoute
  '/app/seo/$id': typeof AppSeoIdRoute
  '/app/seo/$postId': typeof AppSeoPostIdRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/whatsapp/broadcast': typeof AppWhatsappBroadcastRoute
  '/$orgSlug/blog/': typeof OrgSlugBlogIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/app/donors/': typeof AppDonorsIndexRoute
  '/app/receipts/': typeof AppReceiptsIndexRoute
  '/app/seo/': typeof AppSeoIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/whatsapp/': typeof AppWhatsappIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/media': typeof AppMediaRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/upload': typeof AppUploadRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$orgSlug': typeof OrgSlugIndexRoute
  '/admin': typeof AdminIndexRoute
  '/$orgSlug/blog/$postSlug': typeof OrgSlugBlogPostSlugRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
  '/app/donors/$id': typeof AppDonorsIdRoute
  '/app/donors/new': typeof AppDonorsNewRoute
  '/app/receipts/new': typeof AppReceiptsNewRoute
  '/app/seo/$id': typeof AppSeoIdRoute
  '/app/seo/$postId': typeof AppSeoPostIdRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/whatsapp/broadcast': typeof AppWhatsappBroadcastRoute
  '/$orgSlug/blog': typeof OrgSlugBlogIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/app/donors': typeof AppDonorsIndexRoute
  '/app/receipts': typeof AppReceiptsIndexRoute
  '/app/seo': typeof AppSeoIndexRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/whatsapp': typeof AppWhatsappIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/approvals': typeof AppApprovalsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/media': typeof AppMediaRoute
  '/app/submissions': typeof AppSubmissionsRoute
  '/app/upload': typeof AppUploadRoute
  '/invite/$token': typeof InviteTokenRoute
  '/$orgSlug/': typeof OrgSlugIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/$orgSlug/blog/$postSlug': typeof OrgSlugBlogPostSlugRoute
  '/admin/organizations/$id': typeof AdminOrganizationsIdRoute
  '/app/donors/$id': typeof AppDonorsIdRoute
  '/app/donors/new': typeof AppDonorsNewRoute
  '/app/receipts/new': typeof AppReceiptsNewRoute
  '/app/seo/$id': typeof AppSeoIdRoute
  '/app/seo/$postId': typeof AppSeoPostIdRoute
  '/app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/app/settings/team': typeof AppSettingsTeamRoute
  '/app/whatsapp/broadcast': typeof AppWhatsappBroadcastRoute
  '/$orgSlug/blog/': typeof OrgSlugBlogIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/app/donors/': typeof AppDonorsIndexRoute
  '/app/receipts/': typeof AppReceiptsIndexRoute
  '/app/seo/': typeof AppSeoIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/whatsapp/': typeof AppWhatsappIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/dashboard'
    | '/app/media'
    | '/app/submissions'
    | '/app/upload'
    | '/invite/$token'
    | '/$orgSlug/'
    | '/admin/'
    | '/$orgSlug/blog/$postSlug'
    | '/admin/organizations/$id'
    | '/app/donors/$id'
    | '/app/donors/new'
    | '/app/receipts/new'
    | '/app/seo/$id'
    | '/app/seo/$postId'
    | '/app/settings/integrations'
    | '/app/settings/team'
    | '/app/whatsapp/broadcast'
    | '/$orgSlug/blog/'
    | '/admin/organizations/'
    | '/app/donors/'
    | '/app/receipts/'
    | '/app/seo/'
    | '/app/settings/'
    | '/app/whatsapp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/dashboard'
    | '/app/media'
    | '/app/submissions'
    | '/app/upload'
    | '/invite/$token'
    | '/$orgSlug'
    | '/admin'
    | '/$orgSlug/blog/$postSlug'
    | '/admin/organizations/$id'
    | '/app/donors/$id'
    | '/app/donors/new'
    | '/app/receipts/new'
    | '/app/seo/$id'
    | '/app/seo/$postId'
    | '/app/settings/integrations'
    | '/app/settings/team'
    | '/app/whatsapp/broadcast'
    | '/$orgSlug/blog'
    | '/admin/organizations'
    | '/app/donors'
    | '/app/receipts'
    | '/app/seo'
    | '/app/settings'
    | '/app/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/app/analytics'
    | '/app/approvals'
    | '/app/dashboard'
    | '/app/media'
    | '/app/submissions'
    | '/app/upload'
    | '/invite/$token'
    | '/$orgSlug/'
    | '/admin/'
    | '/$orgSlug/blog/$postSlug'
    | '/admin/organizations/$id'
    | '/app/donors/$id'
    | '/app/donors/new'
    | '/app/receipts/new'
    | '/app/seo/$id'
    | '/app/seo/$postId'
    | '/app/settings/integrations'
    | '/app/settings/team'
    | '/app/whatsapp/broadcast'
    | '/$orgSlug/blog/'
    | '/admin/organizations/'
    | '/app/donors/'
    | '/app/receipts/'
    | '/app/seo/'
    | '/app/settings/'
    | '/app/whatsapp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute
  OrgSlugBlogPostSlugRoute: typeof OrgSlugBlogPostSlugRoute
  OrgSlugBlogIndexRoute: typeof OrgSlugBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$orgSlug/': {
      id: '/$orgSlug/'
      path: '/$orgSlug'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/upload': {
      id: '/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AppUploadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/submissions': {
      id: '/app/submissions'
      path: '/submissions'
      fullPath: '/app/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/media': {
      id: '/app/media'
      path: '/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/whatsapp/': {
      id: '/app/whatsapp/'
      path: '/whatsapp'
      fullPath: '/app/whatsapp/'
      preLoaderRoute: typeof AppWhatsappIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seo/': {
      id: '/app/seo/'
      path: '/seo'
      fullPath: '/app/seo/'
      preLoaderRoute: typeof AppSeoIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receipts/': {
      id: '/app/receipts/'
      path: '/receipts'
      fullPath: '/app/receipts/'
      preLoaderRoute: typeof AppReceiptsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/donors/': {
      id: '/app/donors/'
      path: '/donors'
      fullPath: '/app/donors/'
      preLoaderRoute: typeof AppDonorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$orgSlug/blog/': {
      id: '/$orgSlug/blog/'
      path: '/$orgSlug/blog'
      fullPath: '/$orgSlug/blog/'
      preLoaderRoute: typeof OrgSlugBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/whatsapp/broadcast': {
      id: '/app/whatsapp/broadcast'
      path: '/whatsapp/broadcast'
      fullPath: '/app/whatsapp/broadcast'
      preLoaderRoute: typeof AppWhatsappBroadcastRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/team': {
      id: '/app/settings/team'
      path: '/settings/team'
      fullPath: '/app/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/integrations': {
      id: '/app/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/app/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seo/$postId': {
      id: '/app/seo/$postId'
      path: '/seo/$postId'
      fullPath: '/app/seo/$postId'
      preLoaderRoute: typeof AppSeoPostIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/seo/$id': {
      id: '/app/seo/$id'
      path: '/seo/$id'
      fullPath: '/app/seo/$id'
      preLoaderRoute: typeof AppSeoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receipts/new': {
      id: '/app/receipts/new'
      path: '/receipts/new'
      fullPath: '/app/receipts/new'
      preLoaderRoute: typeof AppReceiptsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/donors/new': {
      id: '/app/donors/new'
      path: '/donors/new'
      fullPath: '/app/donors/new'
      preLoaderRoute: typeof AppDonorsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/donors/$id': {
      id: '/app/donors/$id'
      path: '/donors/$id'
      fullPath: '/app/donors/$id'
      preLoaderRoute: typeof AppDonorsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/organizations/$id': {
      id: '/admin/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/admin/organizations/$id'
      preLoaderRoute: typeof AdminOrganizationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$orgSlug/blog/$postSlug': {
      id: '/$orgSlug/blog/$postSlug'
      path: '/$orgSlug/blog/$postSlug'
      fullPath: '/$orgSlug/blog/$postSlug'
      preLoaderRoute: typeof OrgSlugBlogPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrganizationsIdRoute: typeof AdminOrganizationsIdRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminOrganizationsIdRoute: AdminOrganizationsIdRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMediaRoute: typeof AppMediaRoute
  AppSubmissionsRoute: typeof AppSubmissionsRoute
  AppUploadRoute: typeof AppUploadRoute
  AppDonorsIdRoute: typeof AppDonorsIdRoute
  AppDonorsNewRoute: typeof AppDonorsNewRoute
  AppReceiptsNewRoute: typeof AppReceiptsNewRoute
  AppSeoIdRoute: typeof AppSeoIdRoute
  AppSeoPostIdRoute: typeof AppSeoPostIdRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppWhatsappBroadcastRoute: typeof AppWhatsappBroadcastRoute
  AppDonorsIndexRoute: typeof AppDonorsIndexRoute
  AppReceiptsIndexRoute: typeof AppReceiptsIndexRoute
  AppSeoIndexRoute: typeof AppSeoIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppWhatsappIndexRoute: typeof AppWhatsappIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMediaRoute: AppMediaRoute,
  AppSubmissionsRoute: AppSubmissionsRoute,
  AppUploadRoute: AppUploadRoute,
  AppDonorsIdRoute: AppDonorsIdRoute,
  AppDonorsNewRoute: AppDonorsNewRoute,
  AppReceiptsNewRoute: AppReceiptsNewRoute,
  AppSeoIdRoute: AppSeoIdRoute,
  AppSeoPostIdRoute: AppSeoPostIdRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppWhatsappBroadcastRoute: AppWhatsappBroadcastRoute,
  AppDonorsIndexRoute: AppDonorsIndexRoute,
  AppReceiptsIndexRoute: AppReceiptsIndexRoute,
  AppSeoIndexRoute: AppSeoIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppWhatsappIndexRoute: AppWhatsappIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugBlogPostSlugRoute: OrgSlugBlogPostSlugRoute,
  OrgSlugBlogIndexRoute: OrgSlugBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
